---
title: "p8105_hw2_yx3033"
Author: "Yvonne Xie"
Data: "2025-10-01"
output: github_document
---

```{r}
library(tidyverse)
library(dplyr)
```

## Problem 1
Clean pols data set

```{r message=FALSE, warning=FALSE}
pols_df = 
  read_csv("data/pols-month.csv") |> 
  janitor::clean_names() |> 
  separate(mon,into=c("year","month","day")) |> 
  mutate(
    year=as.integer(year),
    month = as.integer(month),
    day = as.integer(day)
  ) |> 
  mutate(month=month.name[month]) |> 
  mutate(president=if_else(prez_gop==1,"gop","dem")) |> 
  select(-prez_dem,-prez_gop,-day)
pols_df
```

clean snv dataset

```{r message=FALSE, warning=FALSE}
snv_df =
  read_csv("data/snp.csv") |> 
  janitor::clean_names() |> 
  separate(date,into=c("month","day","year"), sep="/") |> 
  mutate(
    year = as.integer(if_else(as.integer(year) > 15, paste0("19", year), paste0("20", year))),
    month = as.integer(month),
    day = as.integer(day)
  ) |> 
  mutate(month = month.name[month]) |> 
  select(year, month, close) |> 
  arrange(year, match(month, month.name))
snv_df
```

clean unemployment data set
```{r message=FALSE, warning=FALSE}
unemp_df =
  read_csv("data/unemployment.csv") |> 
  janitor::clean_names() |> 
  pivot_longer(
    cols = jan:dec,
    names_to = "month",
    values_to = "unemployment"
  ) |> 
  mutate(
    month = month.name[match(tolower(month), tolower(month.abb))]
  ) |> 
  select(year, month, unemployment)
unemp_df
```

join snv into pols and merge in unemployment

```{r}
merged_df =
  left_join(pols_df,snv_df, by = c("year", "month")) |> 
  left_join(unemp_df, by = c("year", "month"))
merged_df
```

